name: Linux ARM

on: [push]

jobs:
    build-linux-arm:
        strategy:
            matrix:
                #arch: [armv7, aarch64]
                arch: [aarch64]

        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Get current branch name
          uses: nelonoel/branch-name@v1.0.1

        - name: Run Build
          uses: uraimo/run-on-arch-action@v2
          with:
              arch: ${{matrix.arch}}
              distro: ubuntu22.04
              githubToken: ${{github.token}}  # Not required, but speeds up builds
              install: |
                  apt-get -y update
                  apt-get -y install xvfb  # Needed to run unit tests
                  apt-get -y install cmake
                  apt-get -y install git
                  apt-get -y install g++
                  apt-get -y install qtbase5-dev libqt5svg5-dev
                  apt-get -y install libxcb-cursor0  # Dependencies for "xcb" Qt plugin(actually needed for Qt6)
                  apt-get -y install libocct-data-exchange-dev libocct-draw-dev occt-misc
                  apt-get -y install libtbb2-dev libxi-dev  # Dependencies for OpenCascade v7.5
                  apt-get -y install libassimp-dev

              env: |
                  DISPLAY: :0
                  GIT_BRANCH_NAME: ${{env.BRANCH_NAME}}
                  RUN_ARCH_NAME: ${{matrix.arch}}

              run: |
                  git clone https://github.com/fougue/mayo.git
                  cd mayo
                  echo GIT_BRANCH_NAME=$GIT_BRANCH_NAME
                  # Fixes "fatal: detected dubious ownership in repository at '/home/runner/work/mayo/mayo'"
                  #git config --global --add safe.directory `pwd`
                  git config --global --add safe.directory /home/runner/work/mayo/mayo

                  git checkout $GIT_BRANCH_NAME
                  cd ..
                  mkdir build
                  cd build
                  cmake --version
                  cmake .. \
                        -DMayo_BuildTests=ON \
                        -DMayo_BuildPluginAssimp=ON
                  cmake --build . \
                        --config Release \
                        --parallel `nproc`

                  #
                  # Execute Unit Tests
                  # Note: for some unknown reason unit tests are crashing for armv7(on very first test)
                  #       so just execute them for aarch64
                  #
                  if [ $RUN_ARCH_NAME = 'aarch64' ]; then
                      # Start X11 display server
                      Xvfb $DISPLAY -screen 0 1280x1024x24 &
                      sleep 5s
                      ./mayo --runtests
                  else
                      echo "NOTE: unit tests skipped, they need to be fixed for this architecture"
                  fi
