name: macOS

on: [push]

jobs:
    build-macos:
        runs-on: macos-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Install Qt
          run: brew install qt@5

        - name: Install OpenCascade
          run: brew install opencascade

        - name: Install Assimp
          run: brew install assimp

        - name: Get count of CPU cores
          uses: SimenB/github-actions-cpu-cores@v1
          id: cpu-cores

        - name: Build
          run: |
              mkdir ${{github.workspace}}/build
              cd ${{github.workspace}}/build
              cmake --version
              cmake .. \
                    -DMayo_BuildTests=ON \
                    -DMayo_BuildPluginAssimp=ON \
                    -DQT_DIR=$(brew --prefix qt5)/lib/cmake/Qt5
              cmake --build . \
                    --config Release \
                    --parallel ${{steps.cpu-cores.outputs.count}}

        - name: Execute Unit Tests
          working-directory: ${{github.workspace}}/build
          run: |
              ./mayo.app/Contents/MacOS/mayo --runtests
